spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=uri,baidu

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=uri,qq

        - id: product_route
          uri: lb://xmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://xmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://xmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://xmall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: gulimall_host_route
          uri: lb://xmall-product
          predicates:
            - Path=**.gulimall.comï¼Œitem.gulimall.com

        - id: gulimall_search_route
          uri: lb://xmall-es
          predicates:
            - Path=search.gulimall.com

        - id: gulimall_auth_route
          uri: lb://xmall-auth-server
          predicates:
            - Path=auth.gulimall.com

